name: offline_map
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  mapsforge_flutter: ^2.0.2
  path_provider: ^2.1.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  asset_fill: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/render_themes/
    - packages/mapsforge_flutter/assets/patterns/coniferous.svg
    - packages/mapsforge_flutter/assets/patterns/coniferous_and_deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/dark_farmland.svg
    - packages/mapsforge_flutter/assets/patterns/dark_military.png
    - packages/mapsforge_flutter/assets/patterns/coniferous.svg
    - packages/mapsforge_flutter/assets/patterns/coniferous_and_deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/farmland.svg
    - packages/mapsforge_flutter/assets/patterns/grass.svg
    - packages/mapsforge_flutter/assets/patterns/hills.svg
    - packages/mapsforge_flutter/assets/patterns/quarry.svg
    - packages/mapsforge_flutter/assets/patterns/scrub.svg
    - packages/mapsforge_flutter/assets/patterns/swamp.svg
    - packages/mapsforge_flutter/assets/patterns/access-destination.png
    - packages/mapsforge_flutter/assets/patterns/access-private.png
    - packages/mapsforge_flutter/assets/patterns/arrow.png
    - packages/mapsforge_flutter/assets/patterns/cemetery.png
    - packages/mapsforge_flutter/assets/patterns/deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/dot.png
    - packages/mapsforge_flutter/assets/patterns/farmland.svg
    - packages/mapsforge_flutter/assets/patterns/grass.svg
    - packages/mapsforge_flutter/assets/patterns/hills.svg
    - packages/mapsforge_flutter/assets/patterns/marsh.png
    - packages/mapsforge_flutter/assets/patterns/military.png
    - packages/mapsforge_flutter/assets/patterns/nature-reserve.png
    - packages/mapsforge_flutter/assets/patterns/pike.png
    - packages/mapsforge_flutter/assets/patterns/quarry.svg
    - packages/mapsforge_flutter/assets/patterns/rail.png
    - packages/mapsforge_flutter/assets/patterns/scrub.svg
    - packages/mapsforge_flutter/assets/patterns/swamp.svg
    - packages/mapsforge_flutter/assets/patterns/wood-coniferous.png
    - packages/mapsforge_flutter/assets/patterns/wood-deciduous.png
    - packages/mapsforge_flutter/assets/patterns/wood-mixed.png
    - packages/mapsforge_flutter/assets/symbols/bench.svg
    - packages/mapsforge_flutter/assets/symbols/cable_car.svg
    - packages/mapsforge_flutter/assets/symbols/chair_lift.svg
    - packages/mapsforge_flutter/assets/symbols/dot_black.svg
    - packages/mapsforge_flutter/assets/symbols/dot_blue.svg
    - packages/mapsforge_flutter/assets/symbols/dot_blue_dark.svg
    - packages/mapsforge_flutter/assets/symbols/dot_magenta.svg
    - packages/mapsforge_flutter/assets/symbols/dot_white.svg
    - packages/mapsforge_flutter/assets/symbols/gondola.svg
    - packages/mapsforge_flutter/assets/symbols/oneway.svg
    - packages/mapsforge_flutter/assets/symbols/peak.svg
    - packages/mapsforge_flutter/assets/symbols/railway-crossing-small.svg
    - packages/mapsforge_flutter/assets/symbols/railway-crossing.svg
    - packages/mapsforge_flutter/assets/symbols/traffic_signal.svg
    - packages/mapsforge_flutter/assets/symbols/volcano.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/alpinehut.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/camping.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/caravan_park.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/chalet.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/hostel.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/hotel2.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/shelter2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/firestation3.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/fountain2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/library.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/playground.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/police2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/post_box.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/post_office.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/recycling.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/telephone.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/toilets.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/blocks.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/bollard.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/cycle_barrier.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/gate.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/lift_gate.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/stile.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/fountain2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/library.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/toilets.svg
    - packages/mapsforge_flutter/assets/symbols/custom/money/atm2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/archaeological2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/attraction.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/castle2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/cinema2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/information.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/memorial.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/monument.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/museum.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/ruin.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/theatre.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/view_point.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/windmill.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/zoo.svg
    - packages/mapsforge_flutter/assets/symbols/education/nursery3.svg
    - packages/mapsforge_flutter/assets/symbols/education/school.svg
    - packages/mapsforge_flutter/assets/symbols/education/university.svg
    - packages/mapsforge_flutter/assets/symbols/food/bar.svg
    - packages/mapsforge_flutter/assets/symbols/food/biergarten.svg
    - packages/mapsforge_flutter/assets/symbols/food/cafe.svg
    - packages/mapsforge_flutter/assets/symbols/food/drinkingtap.svg
    - packages/mapsforge_flutter/assets/symbols/food/fastfood.svg
    - packages/mapsforge_flutter/assets/symbols/food/pub.svg
    - packages/mapsforge_flutter/assets/symbols/food/restaurant.svg
    - packages/mapsforge_flutter/assets/symbols/health/doctors2.svg
    - packages/mapsforge_flutter/assets/symbols/health/hospital.svg
    - packages/mapsforge_flutter/assets/symbols/health/pharmacy.svg
    - packages/mapsforge_flutter/assets/symbols/money/atm2.svg
    - packages/mapsforge_flutter/assets/symbols/money/bank2.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/buddhist.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/christian.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/hindu.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/islamic.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/jewish.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/shinto.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/unknown.svg
    - packages/mapsforge_flutter/assets/symbols/poi/cave.svg
    - packages/mapsforge_flutter/assets/symbols/poi/embassy2.svg
    - packages/mapsforge_flutter/assets/symbols/poi/mountain_pass.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/alcohol.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/bakery.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/bicycle.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/book.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/butcher.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/car_repair.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/convenience.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/diy.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/greengrocer.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/laundrette.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/marketplace.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/supermarket.svg
    - packages/mapsforge_flutter/assets/symbols/sport/golf.svg
    - packages/mapsforge_flutter/assets/symbols/sport/shooting.svg
    - packages/mapsforge_flutter/assets/symbols/sport/soccer.svg
    - packages/mapsforge_flutter/assets/symbols/sport/stadium.svg
    - packages/mapsforge_flutter/assets/symbols/sport/swimming_outdoor.svg
    - packages/mapsforge_flutter/assets/symbols/sport/tennis.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/archaeological2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/attraction.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/castle2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/cinema2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/information.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/memorial.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/monument.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/museum.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/picnic.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/ruin.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/theatre.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/view_point.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/windmill.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/zoo.svg
    - packages/mapsforge_flutter/assets/symbols/transport/airport2.svg
    - packages/mapsforge_flutter/assets/symbols/transport/bus_station.svg
    - packages/mapsforge_flutter/assets/symbols/transport/bus_stop.svg
    - packages/mapsforge_flutter/assets/symbols/transport/fuel.svg
    - packages/mapsforge_flutter/assets/symbols/transport/helicopter.svg
    - packages/mapsforge_flutter/assets/symbols/transport/lighthouse.svg
    - packages/mapsforge_flutter/assets/symbols/transport/parking.svg
    - packages/mapsforge_flutter/assets/symbols/transport/parking_private.svg
    - packages/mapsforge_flutter/assets/symbols/transport/rental_bicycle.svg
    - packages/mapsforge_flutter/assets/symbols/transport/slipway.svg
    - packages/mapsforge_flutter/assets/symbols/transport/traffic_lights.svg
    - packages/mapsforge_flutter/assets/symbols/transport/train_station2.svg
    - packages/mapsforge_flutter/assets/symbols/transport/tram_stop.svg
    - packages/mapsforge_flutter/assets/symbols/water/weir.svg
    - packages/mapsforge_flutter/assets/symbols/windsock.svg
    - packages/mapsforge_flutter/assets/symbols/viewpoint.svg
    - assets/map/
    - assets/map/anholt_osmbright/
    - assets/map/anholt_osmbright/12/
    - assets/map/anholt_osmbright/12/2177/
    - assets/map/anholt_osmbright/12/2178/
    - assets/map/anholt_osmbright/12/2179/
    - assets/map/anholt_osmbright/12/2180/
    - assets/map/anholt_osmbright/12/2181/
    - assets/map/anholt_osmbright/13/
    - assets/map/anholt_osmbright/13/4354/
    - assets/map/anholt_osmbright/13/4355/
    - assets/map/anholt_osmbright/13/4356/
    - assets/map/anholt_osmbright/13/4357/
    - assets/map/anholt_osmbright/13/4358/
    - assets/map/anholt_osmbright/13/4359/
    - assets/map/anholt_osmbright/13/4360/
    - assets/map/anholt_osmbright/13/4361/
    - assets/map/anholt_osmbright/13/4362/
    - assets/map/anholt_osmbright/13/4363/
    - assets/map/anholt_osmbright/14/
    - assets/map/anholt_osmbright/14/8709/
    - assets/map/anholt_osmbright/14/8710/
    - assets/map/anholt_osmbright/14/8711/
    - assets/map/anholt_osmbright/14/8712/
    - assets/map/anholt_osmbright/14/8713/
    - assets/map/anholt_osmbright/14/8714/
    - assets/map/anholt_osmbright/14/8715/
    - assets/map/anholt_osmbright/14/8716/
    - assets/map/anholt_osmbright/14/8717/
    - assets/map/anholt_osmbright/14/8718/
    - assets/map/anholt_osmbright/14/8719/
    - assets/map/anholt_osmbright/14/8720/
    - assets/map/anholt_osmbright/14/8721/
    - assets/map/anholt_osmbright/14/8722/
    - assets/map/anholt_osmbright/14/8723/
    - assets/map/anholt_osmbright/14/8724/
    - assets/map/anholt_osmbright/14/8725/
    - assets/map/anholt_osmbright/14/8726/
    - assets/map/anholt_osmbright/14/8727/
    - assets/map/epsg3413/
    - assets/map/tvm/
    - assets/map/tvm/12/
    - assets/map/tvm/12/2922/
    - assets/map/tvm/12/2923/
    - assets/map/tvm/12/2924/
    - assets/map/tvm/13/
    - assets/map/tvm/13/5844/
    - assets/map/tvm/13/5845/
    - assets/map/tvm/13/5846/
    - assets/map/tvm/13/5847/
    - assets/map/tvm/13/5848/
    - assets/map/tvm/13/5849/
    - assets/map/tvm/14/
    - assets/map/tvm/14/11689/
    - assets/map/tvm/14/11690/
    - assets/map/tvm/14/11691/
    - assets/map/tvm/14/11692/
    - assets/map/tvm/14/11693/
    - assets/map/tvm/14/11694/
    - assets/map/tvm/14/11695/
    - assets/map/tvm/14/11696/
    - assets/map/tvm/14/11697/
    - assets/map/tvm/14/11698/
    - assets/map/tvm/14/11699/
    - assets/map/tvm/15/
    - assets/map/tvm/15/23379/
    - assets/map/tvm/15/23380/
    - assets/map/tvm/15/23381/
    - assets/map/tvm/15/23382/
    - assets/map/tvm/15/23383/
    - assets/map/tvm/15/23384/
    - assets/map/tvm/15/23385/
    - assets/map/tvm/15/23386/
    - assets/map/tvm/15/23387/
    - assets/map/tvm/15/23388/
    - assets/map/tvm/15/23389/
    - assets/map/tvm/15/23390/
    - assets/map/tvm/15/23391/
    - assets/map/tvm/15/23392/
    - assets/map/tvm/15/23393/
    - assets/map/tvm/15/23394/
    - assets/map/tvm/15/23395/
    - assets/map/tvm/15/23396/
    - assets/map/tvm/15/23397/
    - assets/map/tvm/15/23398/
    - assets/render_themes/
    

